apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/
  - helmchartrepositories/
  - https://solr.apache.org/operator/downloads/crds/v0.6.0/all-with-dependencies.yaml
  - applications/
