---

SITE_HOST_NAME: localhost
SITE_PORT: 11280
SITE_BASE_URL: http://localhost:11280
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_WARNING_EXCEPTION_SECONDS: 10
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 11281

STATIC_BASE_URL: http://localhost:10880/static
STATIC_PATH: /usr/local/src/eventphenomenon-static

API_CONTACT_EMAIL: 
API_COUNTER_PAUSE: 10
API_COUNTER_RESUME: 5
API_COUNTER_FETCH: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: openlearnx
JDBC_USERNAME: openlearnx
JDBC_PASSWORD: 
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_RESOURCE: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181

SOLR_URL: http://localhost:8983/solr/openlearnx
SOLR_HOST_NAME: localhost
SOLR_PORT: 8983
SOLR_COLLECTION: openlearnx
SOLR_COLLECTION_COMPUTATE: computate
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false

MOONSHOTS_DRIVER_CLASS: com.mysql.cj.jdbc.Driver
MOONSHOTS_HOST: "localhost"
MOONSHOTS_PORT: 3306
MOONSHOTS_DATABASE: "currikidb"
MOONSHOTS_USERNAME: ""
MOONSHOTS_PASSWORD: "*"
MOONSHOTS_FETCH_SIZE: 100
MOONSHOTS_ZONE: UTC

ENABLE_IMPORT_DATA: true

ENABLE_IMPORT_DATA_CurrikiResource: true
#IMPORT_DATA_START_TIME_CurrikiResource: 00:00 America/Denver
#IMPORT_DATA_PERIOD_CurrikiResource: 1 day

# The Auth roles required to be an admin in the site. 
AUTH_ROLES_ADMIN: ['SiteAdmin']
# The Auth roles required to add and modify ChoiceDonor records. 
AUTH_ROLES_REQUIRED_CurrikiResource: ['SiteAdmin']
