---

API_VERSION: 1.0.2
SITE_NAME: smartabyar-smartvillage
SITE_DISPLAY_NAME: Smart Village Project
SITE_PUBLIC_URL: https://smartabyarsmartvillage.org
MAILING_LIST_URL: https://computate.topicbox.com/groups/smartabyar-smartvillage
SITE_HOST_NAME: localhost
SITE_PORT: 12080
SITE_BASE_URL: "http://localhost:12080"
SITE_ZONE: America/New_York
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_MAX_EVENT_LOOP_EXECUTE_TIME: 30
VERTX_MAX_WORKER_EXECUTE_TIME: 6000
VERTX_WARNING_EXCEPTION_SECONDS: 60
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 12081
FACEBOOK_GRAPH_VERSION: v15.0
FACEBOOK_APP_ID: 1871568493111919
GITHUB_ORG: "computate-org"
QUAYIO_ORG: "computateorg"
SITE_POWERED_BY_URL: "https://nerc.mghpcc.org/"
SITE_POWERED_BY_NAME: "NERC"
SITE_POWERED_BY_IMAGE_URI: "/png/nerc/nerc-logo.png"

STATIC_BASE_URL: "http://localhost:12080/static"
STATIC_PATH: "/usr/local/src/smartabyar-smartvillage-static"

API_CONTACT_EMAIL: 
API_COUNTER_RESUME: 0
API_COUNTER_FETCH: 1
API_COUNTER_RESUME_TimeStep: 0
API_COUNTER_FETCH_TimeStep: 1
API_COUNTER_RESUME_VehicleStep: 0
API_COUNTER_FETCH_VehicleStep: 10
API_COUNTER_FETCH_SitePage: 10
API_COUNTER_FETCH_SiteHtm: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: smartvillage
JDBC_USERNAME: smartvillage
JDBC_PASSWORD: password
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_CLIENT: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token
AUTH_FINE_GRAINED_POLICY_PERMISSIONS: false
SSL_VERIFY: true

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181
ZOOKEEPER_BASE_SLEEP_TIME_MILLIS: 5000
ZOOKEEPER_MAX_SLEEP_MILLIS: 5000
ZOOKEEPER_MAX_RETRIES: 5
ZOOKEEPER_CONNECTION_TIMEOUT_MILLIS: 3000
ZOOKEEPER_SESSION_TIMEOUT_MILLIS: 5000

SOLR_URL: https://solr-smartvillage.apps-crc.testing/solr/smartabyar-smartvillage
SOLR_HOST_NAME: solr-smartvillage.apps-crc.testing
SOLR_PORT: 443
SOLR_COLLECTION: smartvillage
SOLR_SSL: true
SOLR_HOST_NAME_COMPUTATE: solr-solr.apps-crc.testing
SOLR_PORT_COMPUTATE: 443
SOLR_COLLECTION_COMPUTATE: computate
SOLR_SSL_COMPUTATE: true
SOLR_URL_COMPUTATE: "https://solr-solr.apps-crc.testing/solr/computate"
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_IotNode: true
ENABLE_REFRESH_DATA_SitePage: true
ENABLE_REFRESH_DATA_SimulationReport: true
ENABLE_REFRESH_DATA_TrafficSimulation: true
ENABLE_REFRESH_DATA_TrafficLightStep: true
ENABLE_REFRESH_DATA_VehicleStep: true
ENABLE_REFRESH_DATA_PersonStep: true
ENABLE_REFRESH_DATA_TrafficLight: true
ENABLE_REFRESH_DATA_TimeStep: true
ENABLE_REFRESH_DATA_BicycleStep: true
ENABLE_REFRESH_DATA_TrafficFlowObserved: true
ENABLE_REFRESH_DATA_SmartTrafficLight: true
ENABLE_REFRESH_DATA_SystemEvent: true
ENABLE_REFRESH_DATA_SiteHtm: true
ENABLE_REFRESH_DATA_IotNodeStep: true
ENABLE_REFRESH_DATA_MapResult: true

ENABLE_IMPORT_DATA: true
ENABLE_IMPORT_DATA_IotNode: true
ENABLE_IMPORT_DATA_SitePage: true
ENABLE_IMPORT_DATA_SimulationReport: true
ENABLE_IMPORT_DATA_TrafficSimulation: true
ENABLE_IMPORT_DATA_TrafficLightStep: true
ENABLE_IMPORT_DATA_VehicleStep: true
ENABLE_IMPORT_DATA_PersonStep: true
ENABLE_IMPORT_DATA_TrafficLight: true
ENABLE_IMPORT_DATA_TimeStep: true
ENABLE_IMPORT_DATA_BicycleStep: true
ENABLE_IMPORT_DATA_TrafficFlowObserved: true
ENABLE_IMPORT_DATA_SmartTrafficLight: true
ENABLE_IMPORT_DATA_SystemEvent: true
ENABLE_IMPORT_DATA_SiteHtm: true
ENABLE_IMPORT_DATA_IotNodeStep: true
ENABLE_IMPORT_DATA_MapResult: true

# The Auth roles required to be an admin in the site. 
AUTH_ROLE_ADMIN: 'SiteAdmin'
# The Auth roles required to add and modify site user records. 
AUTH_ROLE_REQUIRED_SiteUser: 'SiteAdmin'
# The Auth roles required to add and modify IOT node records. 
AUTH_ROLE_REQUIRED_IotNode: 'SiteAdmin'
# The Auth roles required to add and modify article records. 
AUTH_ROLE_REQUIRED_SitePage: 'SiteAdmin'
# The Auth roles required to add and modify simulation report records. 
AUTH_ROLE_REQUIRED_SimulationReport: 'SiteAdmin'
# The Auth roles required to add and modify traffic simulation records. 
AUTH_ROLE_REQUIRED_TrafficSimulation: 'SiteAdmin'
# The Auth roles required to add and modify traffic light step records. 
AUTH_ROLE_REQUIRED_TrafficLightStep: 'SiteAdmin'
# The Auth roles required to add and modify vehicle step records. 
AUTH_ROLE_REQUIRED_VehicleStep: 'SiteAdmin'
# The Auth roles required to add and modify person step records. 
AUTH_ROLE_REQUIRED_PersonStep: 'SiteAdmin'
# The Auth roles required to add and modify traffic light records. 
AUTH_ROLE_REQUIRED_TrafficLight: 'SiteAdmin'
# The Auth roles required to add and modify time step records. 
AUTH_ROLE_REQUIRED_TimeStep: 'SiteAdmin'
# The Auth roles required to add and modify bicycle step records. 
AUTH_ROLE_REQUIRED_BicycleStep: 'SiteAdmin'
# The Auth roles required to add and modify traffic flow observed records. 
AUTH_ROLE_REQUIRED_TrafficFlowObserved: 'SiteAdmin'
# The Auth roles required to add and modify smart traffic light records. 
AUTH_ROLE_REQUIRED_SmartTrafficLight: 'SiteAdmin'
# The Auth roles required to add and modify system event records. 
AUTH_ROLE_REQUIRED_SystemEvent: 'SiteAdmin'
# The Auth roles required to add and modify HTML records. 
AUTH_ROLE_REQUIRED_SiteHtm: 'SiteAdmin'
# The Auth roles required to add and modify IOT node step records. 
AUTH_ROLE_REQUIRED_IotNodeStep: 'SiteAdmin'
# The Auth roles required to add and modify map result records. 
AUTH_ROLE_REQUIRED_MapResult: 'SiteAdmin'

KAFKA_TOPIC_SUMO_RUN: smartvillage-sumo-run
KAFKA_TOPIC_SUMO_STOP: smartvillage-sumo-stop
KAFKA_TOPIC_SUMO_RUN_REPORT: smartvillage-sumo-run-report
KAFKA_TOPIC_SUMO_SIMULATION_INFO: smartvillage-sumo-simulation-info
KAFKA_TOPIC_SUMO_SIMULATION_INFO_PATCH: smartvillage-sumo-simulation-info-patch
KAFKA_TOPIC_SUMO_TRAFFIC_FLOW_OBSERVED_INFO: smartvillage-sumo-traffic-flow-observed-info
KAFKA_TOPIC_SUMO_TRAFFIC_FLOW_OBSERVED_INFO_PATCH: smartvillage-sumo-traffic-flow-observed-info-patch

MQTT_ENABLED: true
MQTT_HOST: fiware-broker-mqtt-nodeport.apps-crc.testing
MQTT_PORT: 30083
MQTT_IOT_SUBSCRIBE_TOPIC: iot/subscribe
